apiVersion: apps/v1
kind: Deployment
metadata:
  name: apilist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apilist
  template:
    metadata:
      labels:
        app: apilist
    spec:
      containers:
        - name: apilist
          image: msergiost/apilist:v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: apilist
spec:
  selector:
    app: apilist
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apilist-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apilist-web
  template:
    metadata:
      labels:
        app: apilist-web
    spec:
      containers:
        - name: apilist-web
          image: msergiost/apilist-web:v1.1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: apilist-web
spec:
  selector:
    app: apilist-web
  ports:
  - port: 81
    targetPort: 80
    name: http
    protocol: TCP
    nodePort: 30001
  type: NodePort