global:
  scrape_interval: 5s
  evaluation_interval: 5s
 
rule_files:
#  - one_rule.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'apilist'  
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081'] 

    basic_auth:
      username: 'admin' 
      password: '1234'