apiVersion: apps/v1
kind: Deployment
metadata:
  name: apilist
  namespace: nsapilist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apilist
  template:
    metadata:
      labels:
        app: apilist
    spec:
      containers:
        - name: apilist
          image: msergiost/apilist:v2.3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          #imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-apilist-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-apilist-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-apilist-secret
                  key: DB_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 180 # Aumente o delay inicial
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 180
          livenessProbe:
            httpGet:
              path: /actuator/health # Endpoint específico para liveness (opcional)
              port: 8080
            initialDelaySeconds: 180 # Começa após o startupProbe
            periodSeconds: 10
            timeoutSeconds: 180
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health # Endpoint específico para readiness (opcional)
              port: 8080
            initialDelaySeconds: 180 # Começa após o startupProbe
            periodSeconds: 5
            timeoutSeconds: 180
            failureThreshold: 3
      #imagePullSecrets:
      #  - name: docker-auth
              #httpHeaders:
              #  - name: token
              #    value: 
---
apiVersion: v1
kind: Service
metadata:
  name: apilist
  namespace: nsapilist
spec:
  selector:
    app: apilist
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apilist-web
  namespace: nsapilist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apilist-web
  template:
    metadata:
      labels:
        app: apilist-web
    spec:
      containers:
        - name: apilist-web
          image: msergiost/apilist-web:v1.1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          #imagePullPolicy: IfNotPresent
          #restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: apilist-web
  namespace: nsapilist
spec:
  selector:
    app: apilist-web
  ports:
  - port: 81
    targetPort: 80
    name: http
    protocol: TCP
    nodePort: 30001
  type: NodePort
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: exec1
#  labels:
#    app: exec1
#spec:
#  containers:
#  - name: exec1
#    image: busybox
#    command: # => EntryPoint
#    - echo
#    args: #=> CMD
#    - "--->>>>>>>>>>>>>> Hello World"
#  restartPolicy: Never
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: exec2
#  labels:
#    app: exec2
#spec:
#  containers:
#  - name: exec2
#    image: busybox
#    command: # => EntryPoint
#      - /bin/sh
#    args: #=> CMD
#      - -c
#      - touch /tmp/teste.txt; sleep 120;
#  restartPolicy: Never

#apiVersion: v1
#kind: namespace
#metadata:
#  name: homologacao