name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    name: "job CI"
    runs-on: ubuntu-latest
    steps: 
      - name: "verificando vers찾o do node"
        run: node --version
      - name: obtendo o c처digo
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22.16.0' # Ou a vers찾o do Node.js que seu projeto utiliza (ex: '20', '16')

      - name: "verificando vers찾o do node depois de instalar"
        run: node --version
        
